=encoding utf8

=head1 ABOUT

This is the update of the Beizer Envelope extension for Inkscape (
L<http://inkscape.org/> - an open-source vector graphics editor) version
0.48.

It is from the original author, GERRIT KARIUS.

— Thanks, Gerrit.

=head1 INSTRUCTIONS

Clone and copy to the Inkscape→ share→ extensions folder.

=cut
