=encoding utf8

=head1 ABOUT

This is the update of the Bezier Envelope extension for Inkscape (
L<http://inkscape.org/> - an open-source vector graphics editor) version
0.48.

It is from the original author, GERRIT KARIUS.

— Thanks, Gerrit.

=head1 INSTRUCTIONS

Clone the repository and copy the C<bezierenvelope.inx> and C<bezierenvelope.py>
files to the “Inkscape→ share→ extensions” folder. The extension can be accessed
using the “Extensions → Modify Path → Bezier Envelope” menu item.
(Not to be confused with the plain “Envelope” menu item)

=cut
